# Generated by Django 4.2.25 on 2025-10-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorDeVisitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='edad',
            field=models.IntegerField(max_length=3),
        ),
    ]
