# Generated by Django 5.2.6 on 2025-10-01 03:11

import GestorDeVisitas.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_s', models.CharField(max_length=50)),
                ('apellido_s', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True, validators=[GestorDeVisitas.validators.validate_rut_chile], verbose_name='RUT')),
                ('visita_activa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='GestorDeVisitas.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='GestorDeVisitas.visitante')),
            ],
        ),
    ]
