# Generated by Django 4.2.25 on 2025-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorDeVisitas', '0002_alter_visitante_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
